### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by olexandr-konovalov** [dylanpeifer/difsets#1] opened 2019-09-03 10:03 UTC
Package tests fail if GAP is loaded with `-A` option to disable loading of the default set of packages: https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master-devel/jobs/580037931

It looks like some dependency is missing in PackageInfo.g

**Comment by fingolfin** [comment] 2019-09-03 21:53
The problem is not a missing dependency, but rather that this code is not reliable:
```
gap> G := SmallGroup(16, 4);;
gap> N := NormalSubgroups(G)[3];;
```
The order of the normal subgroups is *not* uniquely defined, and can change depending on which algorithm is used. If you need a specific subgroup, you should instead give it in terms of the generators of the parent group (assuming *these* are fixed -- they are in the case of groups generated via `SmallGroup`). So here one could use `N:=Subgroup(G, [G.3]);`.

**Comment by dylanpeifer** [comment] 2019-09-04 21:52
You're right, running `gap` gives me

```
gap> G := SmallGroup(16, 4);
<pc group of size 16 with 4 generators>
gap> N := NormalSubgroups(G)[3];
Group([ f1*f2*f3, f3, f4 ])
```

while running `gap -A` gives

```
gap> G := SmallGroup(16, 4);
<pc group of size 16 with 4 generators>
gap> N := NormalSubgroups(G)[3];
Group([ f3 ])
```

which are not even of the same size, causing the index out of range error. I'll adjust this in the tests.

**Comment by dylanpeifer** [comment] 2019-09-04 23:06
As of commit 084ca05, the tests pass for me with `gap` or `gap -A`. This just involved changing from `NormalSubgroups` to `Subgroup` as @fingolfin mentioned. I'm a little worried that I may be using similar things internally. For example, can I rely on `G/N` always returning the same structure and order of elements inside a given GAP session?

I'll take a look at the suggestions in #2 in the next few days. Thanks to both of you for your detailed feedback!

**Comment by fingolfin** [comment] 2019-09-04 23:52
Depends on what you mean with "the same structure and order of elements"... but the answer is probably no. Well, there is some caching of quotients, so it is possible. But some algorithms depend on randomized choice; and loading a package could also affect which code is run, resulting in different results.

**Comment by dylanpeifer** [comment] 2019-09-14 23:00
I put together a new release (2.3.1) which includes the changes to tests mentioned above and the suggestions from #2. Let me know if it passes your tests, and I'll close this issue.

**Comment by olexandr-konovalov** [comment] 2019-09-21 19:37
Thanks @dylanpeifer - tests now pass: https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master-devel/jobs/587281204

**Closed as completed** 2019-09-23 20:46 UTC
